# Generated by Django 5.2.6 on 2025-09-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
    ]
