# Generated by Django 5.2.6 on 2025-09-22 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_location_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'latitude', 'longitude')},
        ),
    ]
