# Generated by Django 5.2.6 on 2025-10-11 23:14

import api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_location_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=api.models.default_end_time),
        ),
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='event',
            name='participant_list',
            field=models.ManyToManyField(blank=True, related_name='joined_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=api.models.default_start_time),
        ),
    ]
