# Generated by Django 5.2.7 on 2025-10-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile'),
        ('api', '0007_comment'),
    ]

    operations = [
    ]
