# Generated by Django 5.2.7 on 2025-10-28 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_0005_profile_0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_club_organizer',
        ),
    ]
