# Generated by Django 5.2.6 on 2025-11-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_usersearch_friendrequest_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('sporting', 'Sporting'), ('tutoring', 'Tutoring'), ('advising', 'Advising'), ('social', 'Social'), ('academic', 'Academic'), ('cultural', 'Cultural'), ('volunteering', 'Volunteering'), ('career', 'Career'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
